### ISSUE TITLE
Custom theme support

### ISSUE THREAD

**Issue by niima** [mamal72/persian-twitter#2]
Hi,
Can you provide a custom theme support so we can have custom css?
I could just add some css in `./app/styles/page-*.css` but I wonder if you like add as a feature like `dark theme` or `wide theme` as switches.

**Comment by mamal72** [comment]
Hm... Having custom CSS and switching between them is not related to this project and can be achieved using extensions like [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en).
As the name of extension says, it's going to be related to localization stuff for the Persian language on Twitter.
