### ISSUE TITLE
Update Vazir font to v19.x

### ISSUE THREAD

**Issue by peymanr34** [mamal72/persian-twitter#7]
Hi, 
Vazir font [has been updated](https://github.com/rastikerdar/vazir-font/releases) with support of Kurdish special letters and it would be great if you update included version with the new one.

Thank you.

**Comment by mamal72** [comment]
I'll make sure to update all the fonts on the new upcoming update to support new Twitter.

**Comment by peymanr34** [comment]
Great, I'm looking forward to it.
